using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace A2v10.AppCompiler;


internal sealed record ClassModel(String Name, String Namespace, String Directory);

[Generator]
public class ClrSoureGenerator : IIncrementalGenerator
{
    const String AttributeSource = """
    // <auto-generated/>
    #nullable enable
    namespace Generated
    {
        [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
        internal sealed class ServerLogicAttribute : global::System.Attribute
        {
        }
    }
    """;

    // Отдельный файл — только глобальная директива. Никаких объявлений типов рядом.
    const String GlobalUsingSource = """
    // <auto-generated/>
    global using Generated;
    """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {

        //if (!Debugger.IsAttached)
            //Debugger.Launch();

        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("markerattr.g.cs", AttributeSource);
            ctx.AddSource("usingattr.g.cs", GlobalUsingSource);
        });

        var attrName = "Generated.ServerLogicAttribute";

        // all metadata.json
        var metadataFiles = context.AdditionalTextsProvider
            .Where(DirectoryFilter.IsMetadataFile)
            .Select(static (addFile, canceletionToken) =>
                (path: DirectoryFilter.DirectoryName(addFile.Path), content: Parse(addFile.GetText(canceletionToken)!.ToString())));

        var metadataDir = metadataFiles.Collect()
            .Select(static (files, _) =>
            {
                var map = new Dictionary<String, String>(StringComparer.OrdinalIgnoreCase);
                foreach (var f in files)
                {
                    if (f.path is null)
                        continue;

                    if (!map.ContainsKey(f.path))
                        // ТУТ ПАРСИМ ???
                        map.Add(f.path, f.content);
                }
                return map;
            });

        // all classes
        var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
            attrName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => ExtractClassModel(ctx)
        )
        .Combine(metadataDir)
        .Select(static (pair, _) =>
        {
            ClassModel model = pair.Left;
            String key = model.Directory;
            return pair.Right.TryGetValue(key, out String? content)
                ? (model, content)
                : (model, null);
        });


        // Пока без компаньона — просто эмитим по файлу на класс,
        // чтобы убедиться, что поток A работает.
        context.RegisterSourceOutput(classes, static (spc, item) =>
        {
            String body = String.IsNullOrEmpty(item.content) ? "// metadata.json NOT FOUND"
                : $"// 1 metadata.json found, {item.content!.Length} chars";
            spc.AddSource(
                 $"{item.model.Namespace}.{item.model.Name}.found.g.cs",
                 $"// 2 found: {item.model.Namespace}.{item.model.Name} @ {item.model.Directory} {body}"
             );
        });
    }
    private static ClassModel ExtractClassModel(GeneratorAttributeSyntaxContext context)
    {
        // TargetSymbol — символ помеченного типа. Тяжёлый; используем здесь,
        // наружу не отдаём.
        INamedTypeSymbol symbol = (INamedTypeSymbol)context.TargetSymbol;

        String name = symbol.Name;

        String ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? String.Empty
            : symbol.ContainingNamespace.ToDisplayString();

        // Путь к .cs-файлу — через синтаксис (раздел 2.3).
        String filePath = context.TargetNode.SyntaxTree.FilePath;
        String directory = DirectoryFilter.DirectoryName(filePath);

        return new ClassModel(name, ns, directory);
    }
}
