using System;
using System.Collections.Generic;
using System.Text;

namespace A2v10.AppCompiler;

internal class Constants
{
    public const String AUTO_GENERATED = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a A2v10.App.Compiler.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        
        /* Copyright © 2025 Oleksandr Kukhtin. All rights reserved.*/
        
        """;
}
