// Copyright © 2022-2026 Oleksandr Kukhtin. All rights reserved.

using System;

namespace A2v10.AppCompiler;

internal class Constants
{
    public const String AUTO_GENERATED = """
        // <auto-generated/>
        //------------------------------------------------------------------------------
        // This code was generated by a A2v10.AppCompiler2026.
        //
        // Changes to this file may cause incorrect behavior and will be lost if
        // the code is regenerated.
        //------------------------------------------------------------------------------
        
        /* Copyright © 2025-2026 Oleksandr Kukhtin. All rights reserved.*/
        
        """;
}
