//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a A2v10.App.Compiler source generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/* Copyright © 2022-2023 Oleksandr Kukhtin. All rights reserved.*/

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO.Compression;
using System.IO;
using System.Text;

namespace $(namespace);

internal static class SampleResourceFile
{
}
