// Copyright © 2022-2026 Oleksandr Kukhtin. All rights reserved.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Collections.Immutable;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;



namespace A2v10.AppCompiler;

/*
    Incremental generator: emits a companion partial per [ServerLogic] class,
    joined to its sibling metadata.json (matched by directory).

    classes + metadata are each Collect()'d, Combined value-to-value, joined via
    a directory map, then SelectMany unspreads them into a per-pair stream.
    The cache boundary sits on each pair: one json edit => one class regenerated.

    metadata.json comes only through AdditionalTextsProvider (disk reads break
    incrementality, RS1035) and is parsed early so the cache keys on the model.
    Pipeline models are light and have value equality.
*/


internal sealed record ClassModel(String Name, String Namespace, String Directory);

[Generator]
public class ClrSourceGenerator : IIncrementalGenerator
{
    const String AttributeSource = $$"""
    // <auto-generated/>
    #nullable enable
    namespace {{Constants.MarkerNamespace}}
    {
        [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
        internal sealed class ServerLogicAttribute : global::System.Attribute
        {
        }
    }
    """;

    // global using only
    const String GlobalUsingSource = $$"""
    // <auto-generated/>
    global using {{Constants.MarkerNamespace}};
    """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {

        //if (!Debugger.IsAttached)
        //Debugger.Launch();

        var rootNs = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
                provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var v)
                    ? v
                    : Constants.MarkerNamespace); // фолбек

        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("markerattr.g.cs", AttributeSource);
            ctx.AddSource("usingattr.g.cs", GlobalUsingSource);
        });


        var attrName = $"{Constants.MarkerNamespace}.ServerLogicAttribute";

        // all metadata.json
        var metadataFiles = context.AdditionalTextsProvider
            .Where(DirectoryFilter.IsMetadataFile)
            .Select(static (addFile, cancellationToken) =>
                MetadataJson.Parse(addFile, cancellationToken)
        ).Collect();

        // all classes
        var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
            attrName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => ExtractClassModel(ctx)
        ).Collect();

        // combine: value x value -> dictionary -> pair collection
        var pairs = classes.Combine(metadataFiles)
            .Select(static (pair, _) =>
            {
                ImmutableArray<ClassModel> classModels = pair.Left;
                ImmutableArray<MetadataJson> jsonModels = pair.Right;

                var map = new Dictionary<String, MetadataJson>(StringComparer.OrdinalIgnoreCase);
                foreach (MetadataJson json in jsonModels)
                {
                    if (!map.ContainsKey(json.Directory))
                        map.Add(json.Directory, json);
                }

                var result = ImmutableArray.CreateBuilder<(ClassModel model, MetadataJson meta)>();
                foreach (ClassModel model in classModels)
                {
                    if (!map.TryGetValue(model.Directory, out var json))
                        json = MetadataJson.Empty(model.Directory);
                    result.Add((model, json));
                }
                return result.ToImmutable();
            });

        // collection -> flow
        var flat = pairs.SelectMany(static (collection, _) => collection);

        context.RegisterSourceOutput(flat.Collect().Combine(rootNs),  
            static (ctx, data) => ClrElementsBuilder.Build(ctx, data.Left, data.Right));
    }
    private static ClassModel ExtractClassModel(GeneratorAttributeSyntaxContext context)
    {
        // TargetSymbol — символ помеченного типа. Тяжёлый; используем здесь,
        // наружу не отдаём.
        INamedTypeSymbol symbol = (INamedTypeSymbol)context.TargetSymbol;

        String name = symbol.Name;

        String ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? String.Empty
            : symbol.ContainingNamespace.ToDisplayString();

        String filePath = context.TargetNode.SyntaxTree.FilePath;
        String directory = DirectoryFilter.DirectoryName(filePath);

        return new ClassModel(name, ns, directory);
    }
}
